export const ENTITY_ORDER = [
  "projects",
  "vacancies",
  "blog",
  "team",
  "appointments",
  "messages",
];

export const ENTITY_CONFIGS = {
  projects: {
    key: "projects",
    route: "/projects",
    label: "Projects",
    singular: "Project",
    description: "Manage portfolio entries, case studies, and current studio work.",
    titleField: "title",
    descriptionField: "summary",
    metaFields: ["category", "location", "year"],
    statusField: "status",
    fields: [
      { name: "title", label: "Project title", type: "text", required: true },
      {
        name: "category",
        label: "Category",
        type: "select",
        required: true,
        options: ["Residential", "Commercial", "Industrial"],
      },
      { name: "location", label: "Location", type: "text", required: true },
      { name: "year", label: "Year", type: "text", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["Draft", "Ongoing Construction", "Completed", "Published"],
      },
      { name: "image", label: "Cover image URL", type: "text" },
      { name: "summary", label: "Summary", type: "textarea" },
      { name: "coordinates", label: "Map Coordinates", type: "text" },
      { name: "publicVisibility", label: "Public Visibility", type: "boolean" },
      { name: "gallery", label: "Gallery", type: "json" },
    ],
  },
  vacancies: {
    key: "vacancies",
    route: "/vacancies",
    label: "Vacancies",
    singular: "Vacancy",
    description: "Create and maintain roles, openings, and hiring visibility.",
    titleField: "title",
    descriptionField: "summary",
    metaFields: ["location", "type", "posted"],
    statusField: "status",
    fields: [
      { name: "title", label: "Role title", type: "text", required: true },
      { name: "location", label: "Location", type: "text", required: true },
      { name: "type", label: "Employment type", type: "text", required: true },
      { name: "posted", label: "Posted date", type: "text", required: true },
      { name: "applicants", label: "Applicants", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["active", "draft", "completed"],
      },
      { name: "summary", label: "Role summary", type: "textarea" },
    ],
  },
  blog: {
    key: "blog",
    route: "/blog",
    label: "Blog Posts",
    singular: "Blog post",
    description: "Publish articles, insights, announcements, and editorial content.",
    titleField: "title",
    descriptionField: "Title ",
    metaFields: ["author", "date"],
    statusField: "status",
    fields: [
      { name: "title", label: "Article title", type: "text", required: true },
      { name: "author", label: "Author", type: "text", required: true },
      { name: "date", label: "Publish date", type: "text", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["active", "draft", "completed"],
      },
      { name: "image", label: "Cover image URL", type: "text" },
      { name: "Title ", label: "Title ", type: "textarea" },
      { name: "body", label: "Body", type: "textarea" },
    ],
  },
  team: {
    key: "team",
    route: "/team",
    label: "Team",
    singular: "Team member",
    description: "Maintain staff profiles, contacts, and role descriptions.",
    titleField: "name",
    descriptionField: "bio",
    metaFields: ["role", "email", "phone"],
    statusField: "status",
    fields: [
      { name: "name", label: "Full name", type: "text", required: true },
      { name: "role", label: "Role", type: "text", required: true },
      { name: "email", label: "Email", type: "text", required: true },
      { name: "phone", label: "Phone", type: "text" },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["active", "ongoing", "draft"],
      },
      { name: "bio", label: "Bio", type: "textarea" },
    ],
  },
  appointments: {
    key: "appointments",
    route: "/appointments",
    label: "Appointments",
    singular: "Appointment",
    description: "Manage consultations, reviews, and scheduled touchpoints.",
    titleField: "client",
    descriptionField: "topic",
    metaFields: ["date", "time", "location"],
    statusField: "status",
    readOnly: true,
    fields: [
      { name: "client", label: "Client", type: "text", required: true },
      { name: "topic", label: "Topic", type: "text", required: true },
      { name: "date", label: "Date", type: "text", required: true },
      { name: "time", label: "Time", type: "text", required: true },
      { name: "location", label: "Location", type: "text" },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["new", "ongoing", "completed", "draft"],
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  messages: {
    key: "messages",
    route: "/messages",
    label: "Messages",
    singular: "Message",
    description: "Update inbound inquiries, replies, and communication notes.",
    titleField: "subject",
    descriptionField: "body",
    metaFields: ["name", "email", "date"],
    statusField: "status",
    readOnly: true,
    fields: [
      { name: "name", label: "Sender name", type: "text", required: true },
      { name: "email", label: "Sender email", type: "text", required: true },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "date", label: "Date", type: "text", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["new", "ongoing", "completed", "draft"],
      },
      { name: "preview", label: "Preview text", type: "textarea" },
      { name: "body", label: "Message body", type: "textarea" },
    ],
  },
};

export function getEntityConfig(entityKey) {
  return ENTITY_CONFIGS[entityKey];
}
