export const ENTITY_ORDER = [
  "projects",
  "media",
  "vacancies",
  "blog",
  "team",
  "appointments",
  "messages",
];

export const PROJECT_STATUSES = ["On Hold", "Ongoing", "Completed"];

export const DEFAULT_PROJECT_CATEGORIES = [
  { id: "project-category-residential", name: "Residential" },
  { id: "project-category-commercial", name: "Commercial" },
  { id: "project-category-industrial", name: "Industrial" },
];

export const ENTITY_CONFIGS = {
  projects: {
    key: "projects",
    route: "/projects",
    label: "Projects",
    singular: "Project",
    description: "Manage portfolio entries, categories, galleries, and project storytelling blocks.",
    titleField: "title",
    descriptionField: "description",
    metaFields: ["category", "status"],
    statusField: "status",
    fields: [
      { name: "title", label: "Project title", type: "text", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: PROJECT_STATUSES,
      },
    ],
  },
  media: {
    key: "media",
    route: "/media",
    label: "Media Library",
    singular: "Media asset",
    description: "Store uploaded images once, enrich them with metadata, and reuse them across the CMS.",
    titleField: "name",
    descriptionField: "caption",
    metaFields: ["mimeType", "createdAt"],
    fields: [
      { name: "name", label: "File name", type: "text" },
      { name: "alt", label: "Alt text", type: "textarea" },
      { name: "caption", label: "Caption", type: "textarea" },
      { name: "url", label: "File URL", type: "text" },
      { name: "mimeType", label: "MIME type", type: "text" },
    ],
  },
  vacancies: {
    key: "vacancies",
    route: "/vacancies",
    label: "Careers",
    singular: "Vacancy",
    description: "Manage job openings, application flow, and candidate visibility from one hiring workspace.",
    titleField: "title",
    descriptionField: "description",
    metaFields: ["status", "updatedAt"],
    statusField: "status",
    fields: [
      { name: "title", label: "Job title", type: "text", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["open", "closed"],
      },
      { name: "description", label: "Job description", type: "textarea" },
    ],
  },
  blog: {
    key: "blog",
    route: "/blog",
    label: "Blog Posts",
    singular: "Blog post",
    description: "Publish articles, insights, announcements, and editorial content.",
    titleField: "title",
    descriptionField: "Title ",
    metaFields: ["author", "date"],
    statusField: "status",
    fields: [
      { name: "title", label: "Article title", type: "text", required: true },
      { name: "author", label: "Author", type: "text", required: true },
      { name: "date", label: "Publish date", type: "text", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["active", "draft", "completed"],
      },
      { name: "image", label: "Cover image URL", type: "text" },
      { name: "Title ", label: "Title ", type: "textarea" },
      { name: "body", label: "Body", type: "textarea" },
    ],
  },
  team: {
    key: "team",
    route: "/team",
    label: "Team",
    singular: "Team member",
    description: "Maintain staff profiles, honorifics, qualifications, and rich biography content.",
    titleField: "name",
    descriptionField: "bio",
    metaFields: ["title", "designation"],
    fields: [
      { name: "title", label: "Title", type: "select", options: ["Mr", "Mrs", "Ms", "Miss", "Arch", "Ar.", "Engr", "Dr", "Prof"] },
      { name: "name", label: "Full name", type: "text", required: true },
      { name: "designation", label: "Designation", type: "text", required: true },
      { name: "qualifications", label: "Qualifications", type: "textarea" },
      { name: "image", label: "Profile picture URL", type: "text" },
      { name: "bio", label: "Bio", type: "textarea" },
    ],
  },
  appointments: {
    key: "appointments",
    route: "/appointments",
    label: "Appointments",
    singular: "Appointment",
    description: "Manage consultations, reviews, and scheduled touchpoints.",
    titleField: "client",
    descriptionField: "topic",
    metaFields: ["date", "time", "location"],
    statusField: "status",
    readOnly: true,
    fields: [
      { name: "client", label: "Client", type: "text", required: true },
      { name: "topic", label: "Topic", type: "text", required: true },
      { name: "date", label: "Date", type: "text", required: true },
      { name: "time", label: "Time", type: "text", required: true },
      { name: "location", label: "Location", type: "text" },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["upcoming", "completed"],
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  messages: {
    key: "messages",
    route: "/messages",
    label: "Messages",
    singular: "Message",
    description: "Update inbound inquiries, replies, and communication notes.",
    titleField: "subject",
    descriptionField: "body",
    metaFields: ["name", "email", "date"],
    statusField: "status",
    readOnly: true,
    fields: [
      { name: "name", label: "Sender name", type: "text", required: true },
      { name: "email", label: "Sender email", type: "text", required: true },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "date", label: "Date", type: "text", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["new", "ongoing", "completed", "draft"],
      },
      { name: "preview", label: "Preview text", type: "textarea" },
      { name: "body", label: "Message body", type: "textarea" },
    ],
  },
};

export function getEntityConfig(entityKey) {
  return ENTITY_CONFIGS[entityKey];
}
